name: S3 Sync

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD:.github/workflows/BuildAndDeploy.yml
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
       
=======
        AWS_REGION: 'ap-south-1' 
>>>>>>> 896ca9522dce643770e4f0194eeff4ff54dc18c8:.github/workflows/main.yml
